export const settings = {
  apiKey: '', baseUrl: 'https://api.openai.com', fallbackPresetNames: [], model: 'gpt-4o',
  subApiKey: '', subBaseUrl: '', subFallbackPresetNames: [], subModel: '',
  embeddingApiKey: '', embeddingBaseUrl: '', embeddingModel: '',
  visionApiKey: '', visionBaseUrl: '', visionModel: '',
  imageApiKey: '', imageBaseUrl: '', imageModel: 'gpt-image-1', imageSize: '1024x1024',
  contextCount: 20, systemPrompt: '', shortReply: false,
  aiName: '炘也', userName: '涂涂', togetherSince: '2026-02-13',
  bgOpacity: 0.3, bgBlur: 0, bubbleOpacity: 0.85,
  streamMode: false,
  ttsType: 'local',
  ttsUrl: 'http://127.0.0.1:9880',
  ttsRefPath: '', ttsRefText: '',
  ttsRefLang: 'zh', ttsTargetLang: 'zh',
  ttsGptWeights: '', ttsSovitsWeights: '',
  ttsPresets: [], ttsAutoPlay: false,
  doubaoAppId: '', doubaoToken: '', doubaoVoice: '', doubaoCluster: 'volcano_tts',
  doubaoProxy: '',
  mosiKey: '', mosiVoiceId: '',
  minimaxKey: '', minimaxGroupId: '', minimaxVoiceId: '', minimaxModel: '', minimaxProxy: '',
  idleRemind: 0, waterRemind: 0, standRemind: 0, dreamEnabled: false, dreamSleepHours: 6,
  memoryArchive: '',
  memoryArchiveCoreMarkers: '',
  memoryArchiveCore: '',
  memoryArchiveAlways: '',
  memoryArchiveExtended: [],
  displayLimit: 0,
  braveKey: '',
  searchDays: 3,
  searchCount: 5,
  forumProxy: '',
  solitudeServerUrl: '',
  moodState: null,
  memoryBank: null,
  bookmarks: [],
};
